name: process

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  process:
    name: Process websites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup dependencies
        run: |-
          python -m pip install --upgrade pipenv wheel
          pipenv install --dev
          pipenv run playwright install
      - name: Run script
        run: pipenv run python process.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
